package org.spider.zwzl;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ArrayBlockingQueue;

import org.spider.util.DateUtil;

public class DoFileSpider {

	private static ArrayBlockingQueue<String> queryDate;

	/**
	 * 文件爬虫 主程序
	 * @param args
	 */
	public static void main(String[] args) {
		doSpider();
	}

	public static void doSpider() {
		System.out.println("文件下载，爬虫程序已启动。。。。。。。");

		System.out.println("数据库连接成功");
		System.out.println("自动生成查询条件");

		List<String> dates = DateUtil.autoGenerateDateArray(DateUtil.getDateFormat(Constants.FILE_DOWNLOAD_END_DATE),
				Constants.FILE_DOWNLOAD_DATE_INTERVAL, DateUtil.getDateFormat(Constants.FILE_DOWNLOAD_START_DATE),
				new ArrayList<String>());

		queryDate = new ArrayBlockingQueue<>(dates.size());
		// 爬取指定日期范围的所有记录
		for (String date : dates) {
			queryDate.add(date);
		}

		for (int i = 0; i < Constants.FILE_DOWNLOAD_MAX_THREAD; i++) {
			FileSpider fileSpider = new FileSpider(queryDate);
			fileSpider.start();
		}
	}
}
