package org.spider.zwzl;

import java.util.ArrayList;
import java.util.List;

import org.jsoup.Jsoup;
import org.jsoup.helper.StringUtil;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import org.spider.util.DateUtil;
import org.spider.zwzl.exception.NotFoundDetailPageException;
import org.spider.zwzl.exception.SpiderCrashException;
import org.spider.zwzl.helper.DownLoadHelper;
import org.spider.zwzl.helper.LoginHelper;
import org.spider.zwzl.helper.PageHelper;
import org.spider.zwzl.helper.QuickHelper;

public class DoFileSpider {

	/**
	 * 文件爬虫 主程序
	 * @param args
	 */
	public static void main(String[] args) {
		HandleExceptionAndReboot(Constants.DEFAULT_END_DATE);
	}

	/**
	 * 爬虫挂了会自动重启
	 * @param endDate
	 */
	private static void HandleExceptionAndReboot(String endDate) {
		try {
			doSpider(endDate);
		} catch (SpiderCrashException e) {
			try {
				Thread.sleep(Constants.REBOOT_WAIT_TIME);
			} catch (InterruptedException e1) {
				e1.printStackTrace();
			}
System.out.println("爬虫挂掉了：正再以指定查询条件重新启动。。。：" + e.getEndDate());
			HandleExceptionAndReboot(e.getEndDate());
		}
	}

	private static void doSpider(String endDate) throws SpiderCrashException {
		System.out.println("爬虫程序已启动。。。。。。。");
		// 挂了重启查询本地文件 并且重启爬虫 重启爬虫的时候的记录日志信息 并且打印

		// cookie 失效后还得重新生成cookie
		String loginCookie = LoginHelper.doLogin();
		System.out.println("模拟登陆成功");
		startSpider(endDate, loginCookie);
	}

	/**
	 * 爬虫程序启动
	 */
	private static void startSpider(String endDate, String loginCookie) throws SpiderCrashException {
		// 动态生成查询条件 然后不断的去爬
		List<String> dates;
		if (StringUtil.isBlank(endDate)) {
			// 为空 则加载默认值
			dates = DateUtil.autoGenerateDateArray(DateUtil.getDateFormat(Constants.FILE_DOWNLOAD_END_DATE), Constants.FILE_DOWNLOAD_DATE_INTERVAL, DateUtil.getDateFormat(Constants.FILE_DOWNLOAD_START_DATE), new ArrayList<String>());
		} else {
			// 不为空 则设置默认值
			dates = DateUtil.autoGenerateDateArray(DateUtil.getDescDateFormat(endDate), Constants.FILE_DOWNLOAD_DATE_INTERVAL, DateUtil.getDateFormat(Constants.FILE_DOWNLOAD_START_DATE), new ArrayList<String>());
		}

		// 爬取指定日期范围的所有记录
		for (String date : dates) {
			System.out.println("开始爬取：" + date + "的数据");
			String zhuanliListHtml = QuickHelper.getQuickListPage(loginCookie, date);
			try {
				spiderListPage(zhuanliListHtml, loginCookie, date);
			} catch (Exception e) {
				throw new SpiderCrashException(date);
			}
			System.out.println("结束爬取：" + date + "的数据");
		}
	}

	/**
	 * 爬取列表页
	 * @param listHtml
	 * @param loginCookie
	 */
	private static void spiderListPage(String listHtml, String loginCookie, String queryBy) {
		Document listPage = Jsoup.parse(listHtml);
		Element mianListContent = listPage.getElementById("notStat2");

		Elements allHref = mianListContent.select("a[href]");
		Element nextHref = null;

		List<String> details = new ArrayList<String>();

		// 找到了下页 链接 和当前页的所有详情
		for (Element element : allHref) {
			String childNodeValue = element.childNode(0).toString().trim();

			if (childNodeValue.equals("[尾页]") || childNodeValue.equals("[下一页]") || childNodeValue.equals("[上一页]") || childNodeValue.equals("[首页]")) {
				if (childNodeValue.equals("[下一页]")) {
					nextHref = element;
				}
			} else {
				String detail = element.attr("href").substring(element.attr("href").lastIndexOf("(") + 2, element.attr("href").lastIndexOf(")") - 1);
				details.add(detail);
			}
		}

		spiderDetailPage(loginCookie, details, queryBy);

		// 获取 recordtotal sWriteDBQuery  20170807-20170808
		if (nextHref != null) {
			String nextHrefValue = nextHref.attr("onclick").toString();
			String currentPage = nextHrefValue.substring(nextHrefValue.indexOf("currPage=") + 9, nextHrefValue.lastIndexOf("\";"));
System.out.println("开始爬取第：" + currentPage + "页");

			String recordtotal = listPage.getElementById("recordtotal").val();

			// 继续爬下页
			String nextPage = PageHelper.queryNextPage(loginCookie, currentPage, queryBy, recordtotal);
			spiderListPage(nextPage, loginCookie, queryBy);
System.out.println("第：" + currentPage + "页爬取结束");
		} else {
			// 列表爬取完成 返回 重新生成查询条件
			return;
		}
	}

	/**
	 * 爬取所有详情页
	 */
	private static void spiderDetailPage(String loginCookie, List<String> details, String queryBy) {
		for (String detail : details) {
			try {
				spiderOneDetailPage(loginCookie, queryBy, detail, Constants.DEFAULT_FAIL_COUNT);
			} catch (Exception e) {
				// 找不到详情页 跳到下一页
				try {
					// 睡眠5秒
					Thread.sleep(5000);
				} catch (InterruptedException e1) {
					e1.printStackTrace();
				}
				System.out.println("当前详情页无法获取,跳过:");
				continue;
			}
		}
	}

	/**
	 * 爬取一张详情页
	 * <p>Title: spiderOneDetailPage</p>
	 * <p>Description: </p>
	 * @param loginCookie
	 * @param queryBy
	 * @param detail
	 * @throws Exception
	 */
	private static void spiderOneDetailPage(String loginCookie, String queryBy, String detail, int faileTimes) throws Exception {
		Document detailDoc = Jsoup.parse(QuickHelper.getDetailPage(detail, loginCookie));
		Element detailContent = detailDoc.getElementById("detailCont");

		if (detailContent != null) {
			Elements hrefs = detailContent.select("a[href]");
			Element downloadHref = null;

			// 在详情页寻到到下载链接
			for (Element element : hrefs) {
				String childNodeValue = element.childNode(0).toString().trim();

				if (childNodeValue.equals("全文浏览")) {
					downloadHref = element;
					break;
				}
			}

			if (downloadHref != null) {
				String onclickValue = downloadHref.attr("onclick");
				onclickValue = onclickValue.substring(onclickValue.lastIndexOf(",") + 2, onclickValue.lastIndexOf(")") -1);
				String[] downloadInfo = onclickValue.split("_");
				String downloadSuffix = downloadInfo[0];
				String downloadLink = "";

				if (downloadSuffix.equals("AN")) {
					downloadLink = DownLoadHelper.doAnGetDownloadHref(loginCookie, downloadInfo[1]);
				} else if (downloadSuffix.equals("PN")) {
					downloadLink = DownLoadHelper.doPnGetDownloadHref(loginCookie, downloadInfo[1]);
				}

	System.out.println("下载链接为：" + downloadLink);
				// 把一次查询所有的下载链接放在安全队列里面 开启多个线程去下载  可能要防止 cookie 过期
				DownLoadHelper.doDownLoad(loginCookie, downloadLink, downloadInfo[1] + Constants.DOWNLOAD_FILE_SUFFIX, queryBy);
			}
		} else {
			System.out.println("detailContent:为空 , 正在重试:当前第 " + faileTimes + " 次");
			if (faileTimes >= Constants.MAX_FAIL_COUNT) {
				throw new NotFoundDetailPageException();
			} else {
				faileTimes += 1;
				spiderOneDetailPage(loginCookie,queryBy ,detail, faileTimes);
			}
		}
	}
}
