package org.spider.zwzl;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ArrayBlockingQueue;

import org.spider.util.DateUtil;
import org.spider.util.MongoDB;
import org.spider.util.MongoUtil;

import com.mongodb.client.MongoCollection;

public class DoMetaDataSpider {

	private static MongoDB mg;

	private static ArrayBlockingQueue<String> queryDate;

	private static MongoCollection<org.bson.Document> coll = MongoUtil.getMogoDbInstance().getCollection();

	/**
	 * 元数据 爬虫主程序
	 *
	 * @param args
	 */
	public static void main(String[] args) {
		doSpider();
	}

	public static void doSpider() {
		System.out.println("元数据，爬虫程序已启动。。。。。。。");

		mg = MongoUtil.getMogoDbInstance();
		System.out.println("数据库连接成功");
		System.out.println("自动生成查询条件");

		List<String> dates = DateUtil.autoGenerateDateArray(DateUtil.getDateFormat(Constants.META_DATA_END_DATE),
				Constants.META_DATA_DATE_INTERVAL, DateUtil.getDateFormat(Constants.META_DATA_START_DATE),
				new ArrayList<String>());

		queryDate = new ArrayBlockingQueue<>(dates.size());
		// 爬取指定日期范围的所有记录
		for (String date : dates) {
			queryDate.add(date);
		}

		for (int i = 0; i < Constants.METADATE_MAX_THREAD; i++) {
			MeteDataSpider meteDataSpider = new MeteDataSpider(queryDate, coll);
			meteDataSpider.start();
		}
	}
}